#!/bin/bash
#SBATCH --job-name=join
#SBATCH --cpus-per-task=36
#SBATCH --mem=2GB
#SBATCH --account=stf
#SBATCH --partition=ckpt
#SBATCH --time=24:00:00
#SBATCH --output=/mmfs1/gscratch/stf/is28/biobias/log1.out
#SBATCH --error=/mmfs1/gscratch/stf/is28/biobias/log1.out

# Run the shell script in the container and overlay
apptainer run --fakeroot --nv -B /gscratch/stf/is28/biobias --overlay /gscratch/stf/is28/Housing/hyak_files/conda-gpu-overlay.img:ro \
/gscratch/stf/is28/pytorch_20.03-py3.sif \
/mmfs1/gscratch/stf/is28/biobias/recreate1.sh